# Generated by Django 5.0.2 on 2024-02-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
    ]
